[package]
name = "ebay_cli"
version = "0.1.0"
authors = ["fluxxu <fluxxu@gmail.com>"]

[dependencies]
clap = "2.31.2"
dotenv = "0.10.1"
ebay = "0.1.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"