[package]
name = "ebay_derive"
version = "0.2.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
syn = "0.15.18"
quote = "0.6.9"
proc-macro2 = "0.4"

[lib]
proc-macro = true
